CREATE TABLE SAMPLE (
    ID NUMBER,
    PWD VARCHAR(30)
);
INSERT INTO SAMPLE VALUES(1,'PASS01');

SELECT*FROM TJOEUN.EMPLOYEE;

INSERT INTO TJOEUN,EMPLOYEE(EMP_ID,EMP_NAME,EMP_NO,JOB_CODE)
        VALUES(400, '아무개','201212-1385769','J2');